services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"

  activemq-artemis:
    image: apache/artemis:latest-alpine
    ports:
      - "61616:61616"
      - "8161:8161"
    environment:
      ARTEMIS_USER: artemis
      ARTEMIS_PASSWORD: artemis