broker.type=rabbitmq
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest
queue.name=pojo-messages

producers.count=1
consumers.count=3
messages.count=1000000

csv.valid.path=valid.csv
csv.invalid.path=invalid.csv