broker.type=activemq
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.passwordd=guest

activemq.host=localhost
activemq.port=61616
activemq.username=artemis
activemq.passwordd=artemis

queue.name=pojo-messages
producers.count=1
consumers.count=3
messages.count=1000000

csv.valid.path=valid.csv
csv.invalid.path=invalid.csv